### ISSUE TITLE
train.prototxt and solver.prototxt

### ISSUE THREAD

**Issue by zhuhongweiyi** [cunjian/face_alignment#1]
Thank you for sahring the code.Could you share me the train.prototxt and solver.prototxt?I want to train by myself.Can you share me the process of train?Thank you very much

**Comment by cunjian** [comment]
Hi, I have uploaded the prototxt, along with the solver file. No big change from the deploy.txt. If you want to train the model by yourself, you need to prepare the data. You can refer to the listed references. This is an ongoing work and I will continue update the project.

**Comment by zhuhongweiyi** [comment]
Thank your reply. I also want to know when i create 300w train_set.txt, whetner i need change the "ratio = 0.1"?
Could you tell me?

**Comment by zhuhongweiyi** [comment]
Thank your reply. I also want to know when i create 300w train_set.txt, whetner i need change the "ratio = 0.1"? and when i flip 19 point ,it show the problem of landmark_flip[[15,17]] = landmark_flip[[17,15]]
IndexError: index 17 is out of bounds for axis 0 with size 15
Could you help me?thank you
